[package]
name = "backends_osx"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "backends_osx"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
libc = "0.2"
mach = "0.3.2"
darwin-libproc = "0.2.0"